function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.internal.t([[
            "/types/array:MyArr",
            { type: "alias", body: { type: "array", valueType: { type: "number" } } }
        ], [
            "/types/array:MyArr2",
            { type: "alias", body: { type: "array", valueType: { type: "string" } } }
        ], [
            "/types/array:MyArr3",
            { type: "alias", body: { type: "array", valueType: { type: "constant", value: null } } }
        ], [
            "/types/array:MyArr4",
            { type: "alias", body: { type: "illegal", file: "/types/array", node: "export type MyArr4 = ArrayLike<5>", message: "References to most of external types are not supported (yet): ArrayLike<5> (of kind TypeReference)" } }
        ], [
            "/types/array:MyArr5",
            { type: "alias", body: { type: "object", properties: {}, index: { keyType: { type: "union", types: [{ type: "string" }, { type: "number" }] }, valueType: { type: "number" } } } }
        ]]);
}
