function (exports, require, __RuntyperAutogeneratedImport, __RuntyperAutogeneratedImport__nartallax_runtyper_1852608213, __RuntyperAutogeneratedImport_fs_1173143189, __RuntyperAutogeneratedImport__nartallax_clamsensor_3886482187) {
    class DogCls {
        constructor() {
            this.name = "Sharique";
        }
        bark() {
        }
    }
    exports.DogCls = DogCls;
    var ClsNamespace;
    (function (ClsNamespace) {
        class CatCls {
            constructor() {
                this.walksOnSelf = true;
            }
            meow() {
            }
        }
        __RuntyperAutogeneratedImport.Runtyper.internal.f([[
                "/types/class_instances:ClsNamespace.CatCls",
                CatCls
            ], [
                "/types/class_instances:ClsNamespace.CatCls.prototype.meow",
                CatCls.prototype.meow
            ]]);
    })(ClsNamespace = exports.ClsNamespace || (exports.ClsNamespace = {}));
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/class_instances:ClsNamespace.CatOrDog",
            { type: "alias", body: { type: "union", types: [{ type: "value_reference", name: "/types/class_instances:ClsNamespace.CatCls" }, { type: "value_reference", name: "/types/class_instances:DogCls" }] } }
        ], [
            "/types/class_instances:MyAnimal",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "/types/class_instances:ClsNamespace.CatOrDog" }, { type: "value_reference", name: "/types/class_instances_to_be_imported:MyHamster" }] } }
        ], [
            "/types/class_instances:MyBuffer",
            { type: "alias", body: { type: "value_reference", name: "@types/node/buffer:Buffer" } }
        ], [
            "/types/class_instances:MyDogs",
            { type: "interface", properties: { firstDog: { type: "value_reference", name: "/types/class_instances:DogCls" }, secondDog: { type: "value_reference", name: "/types/class_instances:DogCls" } } }
        ], [
            "/types/class_instances:MyNyaNyaNya",
            { type: "alias", body: { type: "value_reference", name: "/types/exportequals_to_be_imported:TestNS.MyNyaNya" } }
        ], [
            "/types/class_instances:MyRunner",
            { type: "alias", body: { type: "value_reference", name: "@nartallax/clamsensor/clamsensor:ClamsensorTestRunner" } }
        ], [
            "/types/class_instances:MyValidationError",
            { type: "alias", body: { type: "value_reference", name: "@nartallax/runtyper/runtyper:Runtyper.ValidationError" } }
        ], [
            "/types/class_instances:NamedFile",
            { type: "interface", properties: { name: { type: "string" }, binary: { type: "union", types: [{ type: "value_reference", name: "@types/node/buffer:Buffer" }, { type: "value_reference", name: "typescript/lib/lib.es5:ArrayBuffer" }] }, creationDate: { type: "value_reference", name: "typescript/lib/lib.es5:Date" } } }
        ], [
            "/types/class_instances:StreamOrType",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "@nartallax/runtyper/runtyper:Runtyper.PrimitiveType" }, { type: "value_reference", name: "@types/node/fs:ReadStream" }] } }
        ], [
            "@nartallax/runtyper/runtyper:Runtyper.PrimitiveType",
            { type: "interface", properties: { type: { type: "constant_union", value: ["any", "boolean", "never", "number", "string", "unknown"] } } }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/types/class_instances:ClsNamespace.CatCls",
            { type: "class", instanceProperties: { walksOnSelf: { type: "boolean", access: "public" } }, methods: { meow: { functionName: "/types/class_instances:ClsNamespace.CatCls.prototype.meow", access: "public" } } }
        ], [
            "/types/class_instances:ClsNamespace.CatCls.prototype.meow",
            { type: "function", signatures: [{ hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ], [
            "/types/class_instances:DogCls",
            { type: "class", instanceProperties: { name: { type: "string", access: "public" } }, methods: { bark: { functionName: "/types/class_instances:DogCls.prototype.bark", access: "public" } } }
        ], [
            "/types/class_instances:DogCls.prototype.bark",
            { type: "function", signatures: [{ hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.f([[
            "/types/class_instances:DogCls",
            DogCls
        ], [
            "/types/class_instances:DogCls.prototype.bark",
            DogCls.prototype.bark
        ], [
            "@nartallax/clamsensor/clamsensor:ClamsensorTestRunner",
            __RuntyperAutogeneratedImport__nartallax_clamsensor_3886482187.ClamsensorTestRunner
        ], [
            "@nartallax/runtyper/runtyper:Runtyper.ValidationError",
            __RuntyperAutogeneratedImport__nartallax_runtyper_1852608213.Runtyper.ValidationError
        ], [
            "@types/node/buffer:Buffer",
            Buffer
        ], [
            "@types/node/fs:ReadStream",
            __RuntyperAutogeneratedImport_fs_1173143189.ReadStream
        ], [
            "typescript/lib/lib.es5:ArrayBuffer",
            ArrayBuffer
        ], [
            "typescript/lib/lib.es5:Date",
            Date
        ]]);
}
