function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/constant_types:AnswerToEverything",
            { type: "alias", body: { type: "constant", value: 42 } }
        ], [
            "/types/constant_types:Fraction",
            { type: "alias", body: { type: "constant_union", value: [-0.3, 0.5, 1.5] } }
        ], [
            "/types/constant_types:Goodness",
            { type: "alias", body: { type: "constant_union", value: ["moderately_good", "not_good", "very_good"] } }
        ], [
            "/types/constant_types:MyDogName",
            { type: "alias", body: { type: "constant", value: "I have\" \\ no dog!" } }
        ], [
            "/types/constant_types:MyFalse",
            { type: "alias", body: { type: "constant", value: false } }
        ], [
            "/types/constant_types:MyNull",
            { type: "alias", body: { type: "constant", value: null } }
        ], [
            "/types/constant_types:MyUndefined",
            { type: "alias", body: { type: "constant", value: void 0 } }
        ], [
            "/types/constant_types:Parens",
            { type: "alias", body: { type: "constant_union", value: [1, 2, 3, 4] } }
        ], [
            "/types/constant_types:Quality",
            { type: "alias", body: { type: "constant_union", value: [1, 2, 3, "absolutely_perfect", false, null] } }
        ]]);
}
