function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:AnswerToEverything", { type: "alias", body: { type: "constant", value: 42 } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:Goodness", { type: "alias", body: { type: "constant_union", value: new Set(["very_good", "moderately_good", "not_good"]) } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:MyDogName", { type: "alias", body: { type: "constant", value: "I have\" \\ no dog!" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:MyFalse", { type: "alias", body: { type: "constant", value: false } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:MyNull", { type: "alias", body: { type: "constant", value: null } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:MyUndefined", { type: "alias", body: { type: "constant", value: void 0 } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:Parens", { type: "alias", body: { type: "constant_union", value: new Set([1, 2, 3, 4]) } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/constant_types:Quality", { type: "alias", body: { type: "constant_union", value: new Set([null, false, 1, 2, 3, "absolutely_perfect"]) } });
}
