function (exports, require, tslib_1, __RuntyperAutogeneratedImport, simple_1) {
    var ObjWithExplicitType;
    (function (ObjWithExplicitType) {
        var _a, _b;
        _a = { a: 5, b: { c: 10, d: 15 } }, ObjWithExplicitType.a = _a.a, _b = _a.b, ObjWithExplicitType.c = _b.c, ObjWithExplicitType.d = _b.d;
    })(ObjWithExplicitType || (ObjWithExplicitType = {}));
    var ObjWithoutExplicitType;
    (function (ObjWithoutExplicitType) {
        var _a, _b;
        _a = { a: 5, b: { c: 10, d: 15 } }, ObjWithoutExplicitType.a = _a.a, _b = _a.b, ObjWithoutExplicitType.c = _b.c, ObjWithoutExplicitType.d = _b.d;
    })(ObjWithoutExplicitType || (ObjWithoutExplicitType = {}));
    var ArrayWithExplicitType;
    (function (ArrayWithExplicitType) {
        var _a;
        _a = (0, tslib_1.__read)([1, "f"], 2), ArrayWithExplicitType.c = _a[0], ArrayWithExplicitType.d = _a[1];
    })(ArrayWithExplicitType || (ArrayWithExplicitType = {}));
    var ArrayWithoutExplicitType;
    (function (ArrayWithoutExplicitType) {
        var _a;
        _a = (0, tslib_1.__read)([1, "f"], 2), ArrayWithoutExplicitType.c = _a[0], ArrayWithoutExplicitType.d = _a[1];
    })(ArrayWithoutExplicitType || (ArrayWithoutExplicitType = {}));
    var ObjectRenamingAtDestructurization;
    (function (ObjectRenamingAtDestructurization) {
        var _a;
        _a = { a: 5, b: { c: 10 } }, ObjectRenamingAtDestructurization.aaa = _a.a, ObjectRenamingAtDestructurization.ccc = _a.b.c;
    })(ObjectRenamingAtDestructurization || (ObjectRenamingAtDestructurization = {}));
    var MixedDestr;
    (function (MixedDestr) {
        var _a, _b, _c;
        _a = (0, tslib_1.__read)([null, { a: [6] }], 2), _b = (0, tslib_1.__read)(_a[1].a, 1), MixedDestr.b = _b[0];
        _c = (0, tslib_1.__read)({ c: [{ d: "yep" }] }.c, 1), MixedDestr.d = _c[0].d;
    })(MixedDestr || (MixedDestr = {}));
    var RestDestr;
    (function (RestDestr) {
        var _a, _b;
        _a = (0, tslib_1.__read)([1, 2, 3, 4, 5]), RestDestr.a = _a[0], RestDestr.b = _a[1], RestDestr.c = _a.slice(2);
        _b = (0, tslib_1.__read)({ x: [1, 2, 3, 4, 5] }.x), RestDestr.x = _b[0], RestDestr.y = _b[1], RestDestr.z = _b.slice(2);
    })(RestDestr || (RestDestr = {}));
    var NamedTypedDestruct;
    (function (NamedTypedDestruct) {
        var _a, _b, _c, _d, _e;
        NamedTypedDestruct.x = { x: 5, y: 10 }.x;
        _a = (0, tslib_1.__read)([5, 10], 2), NamedTypedDestruct.y = _a[1];
        _b = (0, tslib_1.__read)([{ x: 5, y: 10 }], 1), NamedTypedDestruct.z = _b[0];
        let pp = { a: { x: 1, y: 1 }, b: { x: 2, y: 2 } };
        NamedTypedDestruct.p = pp.a;
        NamedTypedDestruct.pppppp = pp.a.x;
        let myPoint = { x: 1, y: 2 };
        _c = (0, tslib_1.__read)([[myPoint]], 1), NamedTypedDestruct.ppp = _c[0];
        _d = (0, tslib_1.__read)([[{ x: 1, y: 2 }]], 1), NamedTypedDestruct.pppp = _d[0];
        _e = (0, tslib_1.__read)([[simple_1.typePointToBeRequiredExternally]], 1), NamedTypedDestruct.ppppp = _e[0];
    })(NamedTypedDestruct || (NamedTypedDestruct = {}));
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:MixedTypeB", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:MixedDestr.b" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:MixedTypeD", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:MixedDestr.d" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedDestrA", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:NamedTypedDestruct.p" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedDestrX", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:NamedTypedDestruct.x" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedDestrY", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:NamedTypedDestruct.y" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedDestrZ", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:NamedTypedDestruct.z" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedTypedDestruct.Point", { type: "interface", properties: { x: { type: "number" }, y: { type: "number" } } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedTypedDestruct.Point2", { type: "interface", properties: { x: { type: "generic_parameter", name: "T" }, y: { type: "generic_parameter", name: "T" } }, typeParameters: [{ name: "T" }] });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedTypedDestruct.PointArr", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:NamedTypedDestruct.TwoPoints", { type: "interface", properties: { a: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" }, b: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" } } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:RenamedTypeA", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ObjectRenamingAtDestructurization.aaa" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:RenamedTypeC", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ObjectRenamingAtDestructurization.ccc" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:RestA", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:RestDestr.a" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:RestC", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:RestDestr.c" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:RestZ", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:RestDestr.z" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:TypeFromArrayDestr1", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ArrayWithExplicitType.d" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:TypeFromArrayDestr2", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ArrayWithoutExplicitType.c" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:TypeFromObjDestr1", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ObjWithExplicitType.c" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/destructurizing:TypeFromObjDestr2", { type: "alias", body: { type: "value_reference", name: "/types/destructurizing:ObjWithoutExplicitType.a" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ArrayWithExplicitType.c", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "number" }, { type: "string" }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ArrayWithExplicitType.d", { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "tuple", valueTypes: [{ type: "number" }, { type: "string" }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ArrayWithoutExplicitType.c", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "number" }, { type: "string" }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ArrayWithoutExplicitType.d", { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "tuple", valueTypes: [{ type: "number" }, { type: "string" }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:MixedDestr.b", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "tuple", valueTypes: [{ type: "constant", value: null }, { type: "object", properties: { a: { type: "tuple", valueTypes: [{ type: "number" }] } } }] } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:MixedDestr.d", { type: "index_access", index: { type: "constant", value: "d" }, object: { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "index_access", index: { type: "constant", value: "c" }, object: { type: "object", properties: { c: { type: "tuple", valueTypes: [{ type: "object", properties: { d: { type: "string" } } }] } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.myPoint", { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.p", { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.TwoPoints" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.pp", { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.TwoPoints" });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.ppp", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "array", valueType: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" } }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.pppp", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "array", valueType: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point2", typeArguments: [{ type: "number" }] } }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.ppppp", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "array", valueType: { type: "reference", name: "/types/simple:TypePoint" } }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.pppppp", { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.TwoPoints" } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.x", { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.y", { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "reference", name: "/types/destructurizing:NamedTypedDestruct.PointArr" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:NamedTypedDestruct.z", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "tuple", valueTypes: [{ type: "union", types: [{ type: "reference", name: "/types/destructurizing:NamedTypedDestruct.Point" }, { type: "constant", value: null }] }] } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithExplicitType.a", { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithExplicitType.c", { type: "index_access", index: { type: "constant", value: "c" }, object: { type: "index_access", index: { type: "constant", value: "b" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithExplicitType.d", { type: "index_access", index: { type: "constant", value: "d" }, object: { type: "index_access", index: { type: "constant", value: "b" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithoutExplicitType.a", { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithoutExplicitType.c", { type: "index_access", index: { type: "constant", value: "c" }, object: { type: "index_access", index: { type: "constant", value: "b" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjWithoutExplicitType.d", { type: "index_access", index: { type: "constant", value: "d" }, object: { type: "index_access", index: { type: "constant", value: "b" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" }, d: { type: "number" } } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjectRenamingAtDestructurization.aaa", { type: "index_access", index: { type: "constant", value: "a" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:ObjectRenamingAtDestructurization.ccc", { type: "index_access", index: { type: "constant", value: "c" }, object: { type: "index_access", index: { type: "constant", value: "b" }, object: { type: "object", properties: { a: { type: "number" }, b: { type: "object", properties: { c: { type: "number" } } } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.a", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "array", valueType: { type: "number" } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.b", { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "array", valueType: { type: "number" } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.c", { type: "index_access", index: { type: "constant", value: 2 }, object: { type: "array", valueType: { type: "number" } }, rest: true });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.x", { type: "index_access", index: { type: "constant", value: 0 }, object: { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "object", properties: { x: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }] } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.y", { type: "index_access", index: { type: "constant", value: 1 }, object: { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "object", properties: { x: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }] } } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/destructurizing:RestDestr.z", { type: "index_access", index: { type: "constant", value: 2 }, object: { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "object", properties: { x: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }, { type: "number" }] } } } }, rest: true });
}
