function (exports, require, __RuntyperAutogeneratedImport) {
    var Direction;
    (function (Direction) {
        Direction[Direction["Up"] = 1] = "Up";
        Direction[Direction["Down"] = 2] = "Down";
        Direction[Direction["Left"] = 3] = "Left";
        Direction[Direction["Right"] = 4] = "Right";
    })(Direction = exports.Direction || (exports.Direction = {}));
    var Named;
    (function (Named) {
        Named[Named["B"] = 0] = "B";
        Named["A"] = "sss";
    })(Named = exports.Named || (exports.Named = {}));
    __RuntyperAutogeneratedImport.refTypes.set("/types/enums:Direction", { type: "enum", values: new Set([1, 2, 3, 4]) });
    __RuntyperAutogeneratedImport.refTypes.set("/types/enums:DirectionOrNamed", { type: "alias", body: { type: "union", types: [{ type: "reference", name: "/types/enums:Named" }, { type: "reference", name: "/types/enums:Direction" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/enums:Named", { type: "enum", values: new Set([0, "sss"]) });
}
