function (exports, require, __RuntyperAutogeneratedImport) {
    var TestNS;
    (function (TestNS) {
        class MyNyaNya {
            makeSound() {
                return "cat-cat";
            }
        }
        TestNS.MyNyaNya = MyNyaNya;
        __RuntyperAutogeneratedImport.Runtyper.internal.f([[
                "/types/exportequals_to_be_imported:TestNS.MyNyaNya",
                TestNS.MyNyaNya
            ], [
                "/types/exportequals_to_be_imported:TestNS.MyNyaNya.prototype.makeSound",
                TestNS.MyNyaNya.prototype.makeSound
            ]]);
    })(TestNS || (TestNS = {}));
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/exportequals_to_be_imported:TestNS.Nya",
            { type: "alias", body: { type: "constant", value: "cat" } }
        ], [
            "/types/exportequals_to_be_imported:TestNS.NyaNya",
            { type: "alias", body: { type: "constant", value: "cat-cat" } }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/types/exportequals_to_be_imported:TestNS.MyNyaNya",
            { type: "class", methods: { makeSound: { functionName: "/types/exportequals_to_be_imported:TestNS.MyNyaNya.prototype.makeSound", access: "public" } } }
        ], [
            "/types/exportequals_to_be_imported:TestNS.MyNyaNya.prototype.makeSound",
            { type: "function", signatures: [{ hasImplementation: true, returnType: { type: "type_reference", name: "/types/exportequals_to_be_imported:TestNS.NyaNya" } }] }
        ]]);
    return TestNS;
}
