function (exports, require, __RuntyperAutogeneratedImport) {
    function textField(params) {
        void params;
        return { defaultValue: "" };
    }
    exports.textField = textField;
    function dateField(params) {
        void params;
        return { defaultValue: 0 };
    }
    exports.dateField = dateField;
    exports.CarFields = {
        model: textField({ label: "Model of car" }),
        color: textField({ label: "Color of car" }),
        manufacturingDate: dateField({ label: "Date when car was manufactured" })
    };
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/fields_and_dtos:Car",
            { type: "alias", body: { type: "type_reference", name: "/types/fields_and_dtos:DtoByFields", typeArguments: [{ type: "value_reference", name: "/types/fields_and_dtos:CarFields" }] } }
        ], [
            "/types/fields_and_dtos:DtoByFields",
            { type: "alias", body: { type: "mapped_type", keyName: "P", keyType: { type: "keyof", target: { type: "generic_parameter", name: "T" } }, valueType: { type: "type_reference", name: "/types/fields_and_dtos:FieldType", typeArguments: [{ type: "index_access", index: { type: "generic_parameter", name: "P" }, object: { type: "generic_parameter", name: "T" } }] } }, typeParameters: [{ name: "T" }] }
        ], [
            "/types/fields_and_dtos:FieldDefinition",
            { type: "interface", properties: { defaultValue: { type: "generic_parameter", name: "T" } }, typeParameters: [{ name: "T" }] }
        ], [
            "/types/fields_and_dtos:FieldType",
            { type: "alias", body: { type: "conditional", checkType: { type: "generic_parameter", name: "F" }, extendsType: { type: "type_reference", name: "/types/fields_and_dtos:FieldDefinition", typeArguments: [{ type: "infer", name: "T" }] }, trueType: { type: "generic_parameter", name: "T" }, falseType: { type: "never" } }, typeParameters: [{ name: "F" }] }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/types/fields_and_dtos:CarFields",
            { type: "object", properties: { model: { type: "call_result_reference", functionName: "/types/fields_and_dtos:textField" }, color: { type: "call_result_reference", functionName: "/types/fields_and_dtos:textField" }, manufacturingDate: { type: "call_result_reference", functionName: "/types/fields_and_dtos:dateField" } } }
        ], [
            "/types/fields_and_dtos:dateField",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "params", valueType: { type: "object", properties: { label: { type: "string" } } } }], hasImplementation: true, returnType: { type: "type_reference", name: "/types/fields_and_dtos:FieldDefinition", typeArguments: [{ type: "number" }] } }] }
        ], [
            "/types/fields_and_dtos:textField",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "params", valueType: { type: "object", properties: { label: { type: "string" } } } }], hasImplementation: true, returnType: { type: "type_reference", name: "/types/fields_and_dtos:FieldDefinition", typeArguments: [{ type: "string" }] } }] }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.f([[
            "/types/fields_and_dtos:CarFields",
            exports.CarFields
        ], [
            "/types/fields_and_dtos:dateField",
            dateField
        ], [
            "/types/fields_and_dtos:textField",
            textField
        ]]);
}
