function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.refTypes.set("/types/infer:FieldValue", { type: "alias", body: { type: "conditional", checkType: { type: "generic_parameter", name: "F" }, extendsType: { type: "reference", name: "/types/infer:MyField", typeArguments: [{ type: "infer", name: "Z" }] }, trueType: { type: "generic_parameter", name: "Z" }, falseType: { type: "never" } }, typeParameters: [{ name: "F" }] });
    __RuntyperAutogeneratedImport.refTypes.set("/types/infer:MyField", { type: "interface", properties: { name: { type: "string" }, value: { type: "generic_parameter", name: "T" } }, typeParameters: [{ name: "T" }] });
}
