function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.internal.t([[
            "/types/mapped_types_and_indexed_access:MappedPoint",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "constant_union", value: ["x", "y"] }, valueType: { type: "number" } } }
        ], [
            "/types/mapped_types_and_indexed_access:MyRecordA",
            { type: "interface", properties: { x: { type: "number" } }, index: { keyType: { type: "string" }, valueType: { type: "number" } } }
        ], [
            "/types/mapped_types_and_indexed_access:MyRecordB",
            { type: "alias", body: { type: "object", properties: {}, index: { keyType: { type: "string" }, valueType: { type: "string" } } } }
        ], [
            "/types/mapped_types_and_indexed_access:MyRecordCopyA",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:MyRecordA" } }, valueType: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:MyRecordA" } } } }
        ], [
            "/types/mapped_types_and_indexed_access:MyRecordCopyB",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:MyRecordB" } }, valueType: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:MyRecordB" } } } }
        ], [
            "/types/mapped_types_and_indexed_access:MyRecordCopyBB",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:MyRecordB" } }, valueType: { type: "boolean" } } }
        ], [
            "/types/mapped_types_and_indexed_access:OptionalCopy",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "generic_parameter", name: "T" } }, valueType: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "generic_parameter", name: "T" } }, optional: true }, typeParameters: [{ name: "T" }] }
        ], [
            "/types/mapped_types_and_indexed_access:Point",
            { type: "interface", properties: { x: { type: "number" }, y: { type: "number" } } }
        ], [
            "/types/mapped_types_and_indexed_access:PointCopy",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:Point" } }, valueType: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:Point" } } } }
        ], [
            "/types/mapped_types_and_indexed_access:PointStupidCopy",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:Point" } }, valueType: { type: "index_access", index: { type: "constant", value: "x" }, object: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:Point" } } } }
        ], [
            "/types/mapped_types_and_indexed_access:PointY",
            { type: "alias", body: { type: "index_access", index: { type: "constant", value: "y" }, object: { type: "type_reference", name: "/types/mapped_types_and_indexed_access:Point" } } }
        ], [
            "/types/mapped_types_and_indexed_access:ReadonlyCopy",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "generic_parameter", name: "T" } }, valueType: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "generic_parameter", name: "T" } } }, typeParameters: [{ name: "T" }] }
        ], [
            "/types/mapped_types_and_indexed_access:X",
            { type: "interface", properties: { z: { type: "object", properties: { i: { type: "object", properties: { j: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "generic_parameter", name: "Y" } }, valueType: { type: "number" } } } } } } }, typeParameters: [{ name: "Y" }] }
        ], [
            "/types/mapped_types_and_indexed_access:XX",
            { type: "alias", body: { type: "mapped_type", keyName: "k", keyType: { type: "keyof", target: { type: "generic_parameter", name: "Y" } }, valueType: { type: "object", properties: { z: { type: "object", properties: { i: { type: "object", properties: { j: { type: "index_access", index: { type: "generic_parameter", name: "k" }, object: { type: "generic_parameter", name: "Y" } } } } } } } } }, typeParameters: [{ name: "Y" }] }
        ]]);
}
