function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.refTypes.set("/types/other_module_type_ref:Awoo2", { type: "alias", body: { type: "union", types: [{ type: "reference", name: "/types/simple:SimpleNS2.Awoo" }, { type: "constant", value: "me" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/other_module_type_ref:MyMyMy", { type: "alias", body: { type: "union", types: [{ type: "reference", name: "/types/simple:SimpleNS.MyMy" }, { type: "constant", value: "moo-moo" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/other_module_type_ref:MyStringNumber", { type: "alias", body: { type: "union", types: [{ type: "reference", name: "/types/simple:MyNumber" }, { type: "reference", name: "/types/simple:MyString" }] } });
}
