function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/other_module_type_ref:Awoo2",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "/types/simple:SimpleNS2.Awoo" }, { type: "constant", value: "me" }] } }
        ], [
            "/types/other_module_type_ref:MyMyMy",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "/types/simple:SimpleNS.MyMy" }, { type: "constant", value: "moo-moo" }] } }
        ], [
            "/types/other_module_type_ref:MyStringNumber",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "/types/simple:MyNumber" }, { type: "type_reference", name: "/types/simple:MyString" }] } }
        ]]);
}
