function (exports, require, __RuntyperAutogeneratedImport) {
    exports.typePointToBeRequiredExternally = { x: 1, y: 2 };
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:MyAny", { type: "alias", body: { type: "any" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:MyBool", { type: "alias", body: { type: "boolean" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:MyNumber", { type: "alias", body: { type: "number" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:MyString", { type: "alias", body: { type: "string" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:MyUnknown", { type: "alias", body: { type: "unknown" } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:Point", { type: "interface", properties: { x: { type: "number" }, y: { type: "number" }, z: { type: "number", optional: true } } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:SimpleNS.MyMy", { type: "alias", body: { type: "constant_union", value: new Set(["cow", "dog"]) } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:SimpleNS2.Awoo", { type: "alias", body: { type: "constant_union", value: new Set(["werewolf", "dog"]) } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/simple:TypePoint", { type: "alias", body: { type: "object", properties: { x: { type: "number" }, y: { type: "number", optional: true } } } });
    __RuntyperAutogeneratedImport.valueTypes.set("/types/simple:typePointToBeRequiredExternally", { type: "reference", name: "/types/simple:TypePoint" });
    typeof typePointToBeRequiredExternally === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/types/simple:typePointToBeRequiredExternally", typePointToBeRequiredExternally);
}
