function (exports, require, __RuntyperAutogeneratedImport) {
    exports.typePointToBeRequiredExternally = { x: 1, y: 2 };
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/simple:MyAny",
            { type: "alias", body: { type: "any" } }
        ], [
            "/types/simple:MyBool",
            { type: "alias", body: { type: "boolean" } }
        ], [
            "/types/simple:MyNumber",
            { type: "alias", body: { type: "number" } }
        ], [
            "/types/simple:MyString",
            { type: "alias", body: { type: "string" } }
        ], [
            "/types/simple:MyUnknown",
            { type: "alias", body: { type: "unknown" } }
        ], [
            "/types/simple:Point",
            { type: "interface", properties: { x: { type: "number" }, y: { type: "number" }, z: { type: "number", optional: true } } }
        ], [
            "/types/simple:SimpleNS.MyMy",
            { type: "alias", body: { type: "constant_union", value: ["cow", "dog"] } }
        ], [
            "/types/simple:SimpleNS2.Awoo",
            { type: "alias", body: { type: "constant_union", value: ["dog", "werewolf"] } }
        ], [
            "/types/simple:TypePoint",
            { type: "alias", body: { type: "object", properties: { x: { type: "number" }, y: { type: "number", optional: true } } } }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/types/simple:typePointToBeRequiredExternally",
            { type: "type_reference", name: "/types/simple:TypePoint" }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.f([[
            "/types/simple:typePointToBeRequiredExternally",
            exports.typePointToBeRequiredExternally
        ]]);
}
