function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/tuples:Tuple1",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }] } }
        ], [
            "/types/tuples:Tuple2",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }] } }
        ], [
            "/types/tuples:Tuple3",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "string", optional: true }] } }
        ], [
            "/types/tuples:Tuple4",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "string", optional: true }, { type: "rest", valueType: { type: "boolean" } }] } }
        ], [
            "/types/tuples:Tuple5",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }, { type: "number" }] } }
        ], [
            "/types/tuples:Tuple6",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }, { type: "number" }] } }
        ], [
            "/types/tuples:Tuple7",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }] } }
        ], [
            "/types/tuples:Tuple8",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number", optional: true }, { type: "number", optional: true }, { type: "rest", valueType: { type: "string" } }] } }
        ], [
            "/types/tuples:Tuple9",
            { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number", optional: true }, { type: "number", optional: true }, { type: "rest", valueType: { type: "string" } }] } }
        ]]);
}
