function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple1", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple2", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple3", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "string", optional: true }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple4", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "string", optional: true }, { type: "rest", valueType: { type: "boolean" } }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple5", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }, { type: "number" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple6", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }, { type: "rest", valueType: { type: "string" } }, { type: "number" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple7", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number" }, { type: "number" }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple8", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number", optional: true }, { type: "number", optional: true }, { type: "rest", valueType: { type: "string" } }] } });
    __RuntyperAutogeneratedImport.refTypes.set("/types/tuples:Tuple9", { type: "alias", body: { type: "tuple", valueTypes: [{ type: "number", optional: true }, { type: "number", optional: true }, { type: "rest", valueType: { type: "string" } }] } });
}
