function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/types/union_intersection:ManyMath",
            { type: "alias", body: { type: "intersection", types: [{ type: "type_reference", name: "/types/union_intersection:MathProblem" }, { type: "type_reference", name: "/types/union_intersection:Point" }] } }
        ], [
            "/types/union_intersection:MathAndName",
            { type: "alias", body: { type: "intersection", types: [{ type: "union", types: [{ type: "type_reference", name: "/types/union_intersection:MathProblem" }, { type: "type_reference", name: "/types/union_intersection:Point" }] }, { type: "object", properties: { name: { type: "string" } } }] } }
        ], [
            "/types/union_intersection:MathAndSomethingElse",
            { type: "alias", body: { type: "intersection", types: [{ type: "generic_parameter", name: "T" }, { type: "type_reference", name: "/types/union_intersection:MathProblem" }] }, typeParameters: [{ name: "T" }] }
        ], [
            "/types/union_intersection:MathAndSomethingElseWithDefault",
            { type: "alias", body: { type: "intersection", types: [{ type: "generic_parameter", name: "T" }, { type: "type_reference", name: "/types/union_intersection:MathProblem" }] }, typeParameters: [{ name: "T", default: { type: "type_reference", name: "/types/union_intersection:Point" } }] }
        ], [
            "/types/union_intersection:MathProblem",
            { type: "interface", properties: { x: { type: "number" }, z: { type: "number" } } }
        ], [
            "/types/union_intersection:NotManyMath",
            { type: "alias", body: { type: "union", types: [{ type: "type_reference", name: "/types/union_intersection:MathProblem" }, { type: "type_reference", name: "/types/union_intersection:Point" }] } }
        ], [
            "/types/union_intersection:NullableNumber",
            { type: "alias", body: { type: "union", types: [{ type: "number" }, { type: "constant", value: null }] } }
        ], [
            "/types/union_intersection:Point",
            { type: "interface", properties: { x: { type: "number" }, y: { type: "number" } } }
        ], [
            "/types/union_intersection:Primitive",
            { type: "alias", body: { type: "union", types: [{ type: "number" }, { type: "string" }, { type: "boolean" }] } }
        ], [
            "/types/union_intersection:Shapeless",
            { type: "alias", body: { type: "union", types: [{ type: "any" }, { type: "unknown" }] } }
        ], [
            "/types/union_intersection:Zero",
            { type: "alias", body: { type: "constant_union", value: [null, void 0] } }
        ]]);
}
