function (exports, require, __RuntyperAutogeneratedImport) {
    class ProtoClass {
        constructor() {
            this.protoName = "protoVasya";
        }
    }
    class MyClass extends ProtoClass {
        constructor(whoopsie) {
            super();
            this.whoopsie = whoopsie;
            this.name = "vasya";
        }
        woof(count) {
            return new Array(count + 1).join("woof");
        }
        meow(name) {
            return name + " meow!";
        }
        moo(count) {
            return count === undefined ? "moo!" : ["moo", "moo"];
        }
    }
    exports.MyClass = MyClass;
    MyClass.clsStaticMember = 5;
    exports.myClassInstance = new MyClass(111);
    __RuntyperAutogeneratedImport.refTypes.set("/inferrence/classes:MeowingThing", { type: "interface", properties: { meow: { type: "call_signature", parameters: [{ type: "parameter", name: "name", valueType: { type: "string" } }], returnType: { type: "string" } } } });
    __RuntyperAutogeneratedImport.refTypes.set("/inferrence/classes:MyClsInstanceFieldA", { type: "alias", body: { type: "value_reference", name: "/inferrence/classes:MyClass.prototype.name" } });
    __RuntyperAutogeneratedImport.refTypes.set("/inferrence/classes:MyClsInstanceFieldB", { type: "alias", body: { type: "value_reference", name: "/inferrence/classes:MyClass.prototype.whoopsie" } });
    __RuntyperAutogeneratedImport.refTypes.set("/inferrence/classes:MyClsInstanceFieldC", { type: "alias", body: { type: "value_reference", name: "/inferrence/classes:ProtoClass.prototype.protoName" } });
    __RuntyperAutogeneratedImport.refTypes.set("/inferrence/classes:MyClsStaticField", { type: "alias", body: { type: "value_reference", name: "/inferrence/classes:MyClass.clsStaticMember" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:MyClass", { type: "class", heritage: [{ type: "reference", name: "/inferrence/classes:ProtoClass" }, { type: "reference", name: "/inferrence/classes:MeowingThing" }], instanceProperties: new Map([["name", { type: "string", access: "public" }], ["whoopsie", { type: "number", access: "public" }]]), staticProperties: new Map([["clsStaticMember", { name: "/inferrence/classes:MyClass.clsStaticMember", access: "public" }]]), methods: new Map([["woof", { type: "method", functionName: "/inferrence/classes:MyClass.prototype.woof", access: "public" }], ["meow", { type: "method", functionName: "/inferrence/classes:MyClass.prototype.meow", access: "public" }], ["moo", { type: "method", functionName: "/inferrence/classes:MyClass.prototype.moo", access: "public" }]]) });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:MyClass.clsStaticMember", { type: "number" });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:MyClass.prototype.meow", { type: "function", signatures: [{ type: "call_signature", parameters: [{ type: "parameter", name: "name", valueType: { type: "any" } }], returnType: { type: "string" }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:MyClass.prototype.moo", { type: "function", signatures: [{ type: "call_signature", returnType: { type: "string" } }, { type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" } }], returnType: { type: "array", valueType: { type: "string" } } }, { type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" }, optional: true }], returnType: { type: "union", types: [{ type: "string" }, { type: "array", valueType: { type: "string" } }] }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:MyClass.prototype.woof", { type: "function", signatures: [{ type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" } }], returnType: { type: "string" }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:ProtoClass", { type: "class", instanceProperties: new Map([["protoName", { type: "string", access: "public" }]]) });
    __RuntyperAutogeneratedImport.valueTypes.set("/inferrence/classes:myClassInstance", { type: "reference", name: "/inferrence/classes:MyClass" });
    typeof MyClass === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:MyClass", MyClass);
    typeof MyClass.clsStaticMember === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:MyClass.clsStaticMember", MyClass.clsStaticMember);
    typeof MyClass.prototype.meow === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:MyClass.prototype.meow", MyClass.prototype.meow);
    typeof MyClass.prototype.moo === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:MyClass.prototype.moo", MyClass.prototype.moo);
    typeof MyClass.prototype.woof === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:MyClass.prototype.woof", MyClass.prototype.woof);
    typeof ProtoClass === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:ProtoClass", ProtoClass);
    typeof myClassInstance === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/inferrence/classes:myClassInstance", myClassInstance);
}
