function (exports, require, __RuntyperAutogeneratedImport) {
    class ProtoClass {
        constructor() {
            this.protoName = "protoVasya";
        }
    }
    class MyClass extends ProtoClass {
        constructor(whoopsie) {
            super();
            this.whoopsie = whoopsie;
            this.name = "vasya";
        }
        woof(count) {
            return new Array(count + 1).join("woof");
        }
        meow(name) {
            return name + " meow!";
        }
        moo(count) {
            return count === undefined ? "moo!" : ["moo", "moo"];
        }
    }
    exports.MyClass = MyClass;
    MyClass.clsStaticMember = 5;
    exports.myClassInstance = new MyClass(111);
    class Itrbl {
        [Symbol.iterator]() {
            throw new Error("nope");
        }
    }
    exports.Itrbl = Itrbl;
    __RuntyperAutogeneratedImport.refTypes.set("/values/classes:MeowingThing", { type: "interface", properties: { meow: { type: "call_signature", parameters: [{ type: "parameter", name: "name", valueType: { type: "string" } }], returnType: { type: "string" } } } });
    __RuntyperAutogeneratedImport.refTypes.set("/values/classes:MyClsInstanceFieldA", { type: "alias", body: { type: "value_reference", name: "/values/classes:MyClass.prototype.name" } });
    __RuntyperAutogeneratedImport.refTypes.set("/values/classes:MyClsInstanceFieldB", { type: "alias", body: { type: "value_reference", name: "/values/classes:MyClass.prototype.whoopsie" } });
    __RuntyperAutogeneratedImport.refTypes.set("/values/classes:MyClsInstanceFieldC", { type: "alias", body: { type: "value_reference", name: "/values/classes:ProtoClass.prototype.protoName" } });
    __RuntyperAutogeneratedImport.refTypes.set("/values/classes:MyClsStaticField", { type: "alias", body: { type: "value_reference", name: "/values/classes:MyClass.clsStaticMember" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:Itrbl", { type: "class", heritage: [{ type: "illegal", file: "/values/classes", node: "<unknown>", message: "References to most of external types are not supported (yet): Iterable<null> (of kind ExpressionWithTypeArguments)" }], methods: new Map([["[Symbol.iterator]", { type: "method", functionName: "/values/classes:Itrbl.prototype.[Symbol.iterator]", access: "public" }]]) });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:Itrbl.prototype.[Symbol.iterator]", { type: "function", signatures: [{ type: "call_signature", returnType: { type: "never" }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:MyClass", { type: "class", heritage: [{ type: "reference", name: "/values/classes:ProtoClass" }, { type: "reference", name: "/values/classes:MeowingThing" }], instanceProperties: new Map([["name", { type: "string", access: "public" }], ["whoopsie", { type: "number", access: "public" }]]), staticProperties: new Map([["clsStaticMember", { name: "/values/classes:MyClass.clsStaticMember", access: "public" }]]), methods: new Map([["woof", { type: "method", functionName: "/values/classes:MyClass.prototype.woof", access: "public" }], ["meow", { type: "method", functionName: "/values/classes:MyClass.prototype.meow", access: "public" }], ["moo", { type: "method", functionName: "/values/classes:MyClass.prototype.moo", access: "public" }]]) });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:MyClass.clsStaticMember", { type: "number" });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:MyClass.prototype.meow", { type: "function", signatures: [{ type: "call_signature", parameters: [{ type: "parameter", name: "name", valueType: { type: "any" } }], returnType: { type: "string" }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:MyClass.prototype.moo", { type: "function", signatures: [{ type: "call_signature", returnType: { type: "string" } }, { type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" } }], returnType: { type: "array", valueType: { type: "string" } } }, { type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" }, optional: true }], returnType: { type: "union", types: [{ type: "string" }, { type: "array", valueType: { type: "string" } }] }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:MyClass.prototype.woof", { type: "function", signatures: [{ type: "call_signature", parameters: [{ type: "parameter", name: "count", valueType: { type: "number" } }], returnType: { type: "string" }, hasImplementation: true }] });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:ProtoClass", { type: "class", instanceProperties: new Map([["protoName", { type: "string", access: "public" }]]) });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/classes:myClassInstance", { type: "reference", name: "/values/classes:MyClass" });
    typeof Itrbl === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:Itrbl", Itrbl);
    typeof Itrbl.prototype[Symbol.iterator] === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:Itrbl.prototype.[Symbol.iterator]", Itrbl.prototype[Symbol.iterator]);
    typeof MyClass === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:MyClass", MyClass);
    typeof MyClass.clsStaticMember === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:MyClass.clsStaticMember", MyClass.clsStaticMember);
    typeof MyClass.prototype.meow === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:MyClass.prototype.meow", MyClass.prototype.meow);
    typeof MyClass.prototype.moo === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:MyClass.prototype.moo", MyClass.prototype.moo);
    typeof MyClass.prototype.woof === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:MyClass.prototype.woof", MyClass.prototype.woof);
    typeof ProtoClass === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:ProtoClass", ProtoClass);
    typeof exports.myClassInstance === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/classes:myClassInstance", exports.myClassInstance);
}
