function (exports, require, __RuntyperAutogeneratedImport) {
    let x = 5;
    let y = "asdasd";
    const qwert = 5;
    let rewq = 5;
    let xx = x;
    let yy = y;
    let zz = false;
    const zzz = (false);
    let qwert2 = qwert;
    let rewq2 = rewq;
    let rewq3 = 5;
    let wut = x;
    __RuntyperAutogeneratedImport.internal.t([[
            "/values/exclamation_token:QwertNoEmptyVal",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:qwert2" } }
        ], [
            "/values/exclamation_token:RewqInlineNoEmptyVal",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:rewq3" } }
        ], [
            "/values/exclamation_token:RewqNoEmptyVal",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:rewq2" } }
        ], [
            "/values/exclamation_token:ThisShoultBeNever",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:wut" } }
        ], [
            "/values/exclamation_token:XNoNull",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:xx" } }
        ], [
            "/values/exclamation_token:YNoUndef",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:yy" } }
        ], [
            "/values/exclamation_token:ZConstNoEmptyVal",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:zzz" } }
        ], [
            "/values/exclamation_token:ZNoEmptyVal",
            { type: "alias", body: { type: "value_reference", name: "/values/exclamation_token:zz" } }
        ]]);
    __RuntyperAutogeneratedImport.internal.v([[
            "/values/exclamation_token:qwert",
            { type: "constant", value: 5 }
        ], [
            "/values/exclamation_token:qwert2",
            { type: "non_null", valueType: { type: "value_reference", name: "/values/exclamation_token:qwert" } }
        ], [
            "/values/exclamation_token:rewq",
            { type: "constant_union", value: [5, null, void 0] }
        ], [
            "/values/exclamation_token:rewq2",
            { type: "non_null", valueType: { type: "value_reference", name: "/values/exclamation_token:rewq" } }
        ], [
            "/values/exclamation_token:rewq3",
            { type: "constant", value: 5 }
        ], [
            "/values/exclamation_token:wut",
            { type: "never" }
        ], [
            "/values/exclamation_token:x",
            { type: "union", types: [{ type: "number" }, { type: "constant", value: null }] }
        ], [
            "/values/exclamation_token:xx",
            { type: "non_null", valueType: { type: "value_reference", name: "/values/exclamation_token:x" } }
        ], [
            "/values/exclamation_token:y",
            { type: "union", types: [{ type: "string" }, { type: "constant", value: void 0 }] }
        ], [
            "/values/exclamation_token:yy",
            { type: "non_null", valueType: { type: "value_reference", name: "/values/exclamation_token:y" } }
        ], [
            "/values/exclamation_token:zz",
            { type: "boolean" }
        ], [
            "/values/exclamation_token:zzz",
            { type: "constant", value: false }
        ]]);
    __RuntyperAutogeneratedImport.internal.f([[
            "/values/exclamation_token:qwert",
            qwert
        ], [
            "/values/exclamation_token:qwert2",
            qwert2
        ], [
            "/values/exclamation_token:rewq",
            rewq
        ], [
            "/values/exclamation_token:rewq2",
            rewq2
        ], [
            "/values/exclamation_token:rewq3",
            rewq3
        ], [
            "/values/exclamation_token:wut",
            wut
        ], [
            "/values/exclamation_token:x",
            x
        ], [
            "/values/exclamation_token:xx",
            xx
        ], [
            "/values/exclamation_token:y",
            y
        ], [
            "/values/exclamation_token:yy",
            yy
        ], [
            "/values/exclamation_token:zz",
            zz
        ], [
            "/values/exclamation_token:zzz",
            zzz
        ]]);
}
