function (exports, require, __RuntyperAutogeneratedImport) {
    function mul2(value) {
        return value * 2;
    }
    exports.mul2 = mul2;
    let varFunc = x => x === "5" ? 5 : null;
    exports.varFunc = varFunc;
    let varFunc2 = (x) => console.log(x);
    exports.varFunc2 = varFunc2;
    exports.varFunc3 = (x => console.log(x));
    function destFn({ a, b }) {
        console.log(b, a);
    }
    exports.destFn = destFn;
    function valueOrDefault(value) {
        return value || 5;
    }
    exports.valueOrDefault = valueOrDefault;
    function valueOrDefault2(value = 5) {
        return value;
    }
    exports.valueOrDefault2 = valueOrDefault2;
    function reverseType(x) {
        return x;
    }
    exports.reverseType = reverseType;
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/values/functions:destFn",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", valueType: { type: "object", properties: { a: { type: "number" }, b: { type: "string" } } } }], hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ], [
            "/values/functions:mul2",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "value", valueType: { type: "number" } }], hasImplementation: true, returnType: { type: "number" } }] }
        ], [
            "/values/functions:reverseType",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "number" } }], returnType: { type: "string" } }, { parameters: [{ type: "parameter", name: "x", valueType: { type: "string" } }], returnType: { type: "number" } }, { parameters: [{ type: "parameter", name: "x", valueType: { type: "union", types: [{ type: "string" }, { type: "number" }] } }], hasImplementation: true, returnType: { type: "union", types: [{ type: "string" }, { type: "number" }] } }] }
        ], [
            "/values/functions:valueOrDefault",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "value", valueType: { type: "number" }, optional: true }], hasImplementation: true, returnType: { type: "number" } }] }
        ], [
            "/values/functions:valueOrDefault2",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "value", valueType: { type: "number" }, optional: true }], hasImplementation: true, returnType: { type: "number" } }] }
        ], [
            "/values/functions:varFunc",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "string" } }], returnType: { type: "union", types: [{ type: "number" }, { type: "constant", value: null }] } }] }
        ], [
            "/values/functions:varFunc2",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "number" } }], hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ], [
            "/values/functions:varFunc3",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "number" } }], returnType: { type: "constant", value: void 0 } }] }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.f([[
            "/values/functions:destFn",
            destFn
        ], [
            "/values/functions:mul2",
            mul2
        ], [
            "/values/functions:reverseType",
            reverseType
        ], [
            "/values/functions:valueOrDefault",
            valueOrDefault
        ], [
            "/values/functions:valueOrDefault2",
            valueOrDefault2
        ], [
            "/values/functions:varFunc",
            exports.varFunc
        ], [
            "/values/functions:varFunc2",
            exports.varFunc2
        ], [
            "/values/functions:varFunc3",
            exports.varFunc3
        ]]);
}
