function (exports, require, __RuntyperAutogeneratedImport, runtyper_1) {
    exports.pointStructure = { type: "type_reference", name: "/types/simple:Point" };
    exports.numberStructure = { type: "number" };
    exports.pointCopyStructure = { type: "object", properties: { x: { type: "number" }, y: { type: "number" } } };
    exports.constStructure = { type: "constant_union", value: [5, "nope"] };
    __RuntyperAutogeneratedImport.Runtyper.internal.v([[
            "/values/get_type:constStructure",
            { type: "call_result_reference", functionName: "/node_modules/runtyper/runtyper.d:Runtyper.getType" }
        ], [
            "/values/get_type:numberStructure",
            { type: "call_result_reference", functionName: "/node_modules/runtyper/runtyper.d:Runtyper.getType" }
        ], [
            "/values/get_type:pointCopyStructure",
            { type: "call_result_reference", functionName: "/node_modules/runtyper/runtyper.d:Runtyper.getType" }
        ], [
            "/values/get_type:pointStructure",
            { type: "call_result_reference", functionName: "/node_modules/runtyper/runtyper.d:Runtyper.getType" }
        ]]);
    __RuntyperAutogeneratedImport.Runtyper.internal.f([[
            "/values/get_type:constStructure",
            exports.constStructure
        ], [
            "/values/get_type:numberStructure",
            exports.numberStructure
        ], [
            "/values/get_type:pointCopyStructure",
            exports.pointCopyStructure
        ], [
            "/values/get_type:pointStructure",
            exports.pointStructure
        ]]);
}
