function (exports, require, __RuntyperAutogeneratedImport) {
    var NestedA;
    (function (NestedA) {
        let NestedB;
        (function (NestedB) {
            let NestedC;
            (function (NestedC) {
                let NestedD;
                (function (NestedD) {
                    NestedD.veryNestedVar = (x) => console.log(x);
                    function veryNestedFn(x) {
                        console.log(x);
                    }
                    NestedD.veryNestedFn = veryNestedFn;
                    __RuntyperAutogeneratedImport.internal.f([[
                            "/values/namespaces:NestedA.NestedB.NestedC.NestedD.veryNestedFn",
                            NestedD.veryNestedFn
                        ], [
                            "/values/namespaces:NestedA.NestedB.NestedC.NestedD.veryNestedVar",
                            NestedD.veryNestedVar
                        ]]);
                })(NestedD = NestedC.NestedD || (NestedC.NestedD = {}));
            })(NestedC = NestedB.NestedC || (NestedB.NestedC = {}));
        })(NestedB = NestedA.NestedB || (NestedA.NestedB = {}));
    })(NestedA = exports.NestedA || (exports.NestedA = {}));
    __RuntyperAutogeneratedImport.internal.v([[
            "/values/namespaces:NestedA.NestedB.NestedC.NestedD.veryNestedFn",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "string" } }], hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ], [
            "/values/namespaces:NestedA.NestedB.NestedC.NestedD.veryNestedVar",
            { type: "function", signatures: [{ parameters: [{ type: "parameter", name: "x", valueType: { type: "number" } }], hasImplementation: true, returnType: { type: "constant", value: void 0 } }] }
        ]]);
}
