function (exports, require, __RuntyperAutogeneratedImport, SimpleModule) {
    exports.otherConstBasedOnAnotherConst = { ...SimpleModule.typePointToBeRequiredExternally };
    __RuntyperAutogeneratedImport.refTypes.set("/values/tricky_imports:TTTTTT", { type: "alias", body: { type: "value_reference", name: "/types/simple:typePointToBeRequiredExternally" } });
    __RuntyperAutogeneratedImport.refTypes.set("/values/tricky_imports:ZZZZZZ", { type: "alias", body: { type: "illegal", file: "/values/tricky_imports", node: "export type ZZZZZZ = typeof NestedA.NestedB.NestedC.NestedD.veryNestedFn;", message: "Cannot understand type of typeof target declaration: typeof NestedA.NestedB.NestedC.NestedD.veryNestedFn (of kind TypeQuery)" } });
    __RuntyperAutogeneratedImport.valueTypes.set("/values/tricky_imports:otherConstBasedOnAnotherConst", { type: "object", properties: { x: { type: "number" }, y: { type: "union", types: [{ type: "number" }, { type: "constant", value: void 0 }], optional: true } } });
    typeof exports.otherConstBasedOnAnotherConst === "function" && __RuntyperAutogeneratedImport.functionsByName.set("/values/tricky_imports:otherConstBasedOnAnotherConst", exports.otherConstBasedOnAnotherConst);
}
