function (exports, require, __RuntyperAutogeneratedImport) {
    __RuntyperAutogeneratedImport.Runtyper.internal.t([[
            "/values/tricky_imports:TTTTTT",
            { type: "alias", body: { type: "value_reference", name: "/types/simple:typePointToBeRequiredExternally" } }
        ], [
            "/values/tricky_imports:ZZZZZZ",
            { type: "alias", body: { type: "value_reference", name: "/values/namespaces:NestedA.NestedB.NestedC.NestedD.veryNestedFn" } }
        ], [
            "/values/tricky_imports:asdasdas",
            { type: "alias", body: { type: "value_reference", name: "/types/simple:typePointToBeRequiredExternally" } }
        ]]);
}
